# Generated by Django 4.2.25 on 2025-11-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
    ]
