# Generated by Django 4.2.25 on 2025-11-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_duration'),
    ]

    operations = [
        # Изменяем поле album: делаем его обязательным (убираем null=True, blank=True)
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='songs',
                to='music.album'
            ),
        ),
    ]
